name: Deploy Vite + React App to GitHub Pages

on:
  push:
    branches:
      - main            # main 分支有變更就部署
  workflow_dispatch:     # 手動觸發也可以

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 取得程式碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 設定 Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 安裝相依套件
      - name: Install dependencies
        run: npm ci

      # 4. Build
      - name: Build with Vite
        run: npm run build

      # 5. Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
